//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smps.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int EmpNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public string UserLoginId { get; set; }
        public string UserLoginPassword { get; set; }
        public string UserType { get; set; }
        public string ParkingSlotNumber { get; set; }
        public string Location { get; set; }
        public short OperationType { get; set; }
    }
}
